name: 'Upgrade provider'
description: 'An action to upgrade bridged providers'
inputs:
  kind:
    description: The kind of upgrade to perform; valid options are ["all", "provider", "bridge"]
    required: true
    default: "all"
runs:
  using: "composite"
  steps:
  - name: Install Go
    uses: actions/setup-go@v3
    with:
      go-version: 1.20.1
  - name: Install pulumictl
    uses: jaxxstorm/action-install-gh-release@v1.5.0
    with:
      repo: pulumi/pulumictl
  - name: Install Pulumi CLI
    uses: pulumi/action-install-pulumi-cli@v2
  - name: Checkout repo
    uses: actions/checkout@v3
    with:
      ref: ${{ github.ref_name }}
  - name: Install upgrade-provider
    run: go install github.com/pulumi/upgrade-provider@3ca72093a40d4c2809145cb96e4a4a8906612c1f
    shell: bash
  - name: Setup Gradle
    uses: gradle/gradle-build-action@v2
    with:
      gradle-version: "7.6"
  - name: Set up git identity
    run: git config --global user.name ${{ github.event.issue.user.login }}
    shell: bash
  - name: Run upgrade-provider
    run: upgrade-provider ${{ github.repository }} --kind=all
    shell: bash
    env:
      GH_TOKEN: ${{ env.GH_TOKEN }}
